CREATE TABLE `base_address` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `store` varchar(64) NOT NULL DEFAULT '',
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `country_code` varchar(64) DEFAULT NULL,
  `state_code` varchar(64) DEFAULT NULL,
  `city_code` varchar(64) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `alias` varchar(64) DEFAULT NULL,
  `first_name` varchar(128) NOT NULL DEFAULT '',
  `last_name` varchar(128) NOT NULL DEFAULT '',
  `email` varchar(128) NOT NULL DEFAULT '',
  `address1` varchar(128) NOT NULL DEFAULT '',
  `address2` varchar(128) DEFAULT NULL,
  `postcode` varchar(64) DEFAULT NULL,
  `phone` varchar(64) DEFAULT NULL,
  `phone_mobile` varchar(64) DEFAULT NULL,
  `registered_as` varchar(128) DEFAULT NULL,
  `note` varchar(500) DEFAULT '',
  `created_by` bigint(20) unsigned NOT NULL,
  `updated_by` bigint(20) unsigned NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `city_state_country` (`city_code`,`state_code`,`country_code`),
  KEY `user_registered_store` (`user_id`,`registered_as`,`store`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;